# Generated by Django 3.2.6 on 2021-08-19 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_calendar', '0003_auto_20210819_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryholidays',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to=settings.AUTH_USER_MODEL),
        ),
    ]
